databases:
  - name: my_postgres_db
    plan: free
    databaseName: myapp_db
    user: myapp_user

services:
  - type: web
    name: fastify-app
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run migrate && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: my_postgres_db
          property: connectionString
    autoDeploy: false

version: "1"